services:
  file-storage-frontend:
    build:
      context: ./frontend/roadmap-cloud-storage-frontend-master/
      dockerfile: Dockerfile
    container_name: file-storage-frontend
    ports:
      - "8086:80"
    networks:
      - file-storage-network

  file-storage-postgres-db:
    image: postgres:15-alpine
    container_name: file-storage-postgres-db
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - file-storage-network

  file-storage-minio:
    image: minio/minio
    container_name: file-storage-minio
    env_file:
      - .env.dev
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - file-storage-network

  minio-create-buckets:
    image: minio/mc
    depends_on:
      - file-storage-minio
    networks:
      - file-storage-network
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://file-storage-minio:9000 admin password;
        mc mb -p local/user-files;
        mc policy set public local/user-files;
        exit 0;
      "

  file-storage-redis:
    image: redis:latest
    container_name: session-storage-redis
    command: ["redis-server", "--requirepass", "password"]
    env_file:
      - .env.dev
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - file-storage-network

volumes:
  postgres-data:
  minio-data:
  redis-data:

networks:
  file-storage-network:
    driver: bridge


