server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false
  port: ${SPRING_SERVER_PORT}

spring:
  config:
    import: optional:file:.env.dev[.properties]
    activate:
      on-profile: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:5MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:15MB}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      default_schema: ${POSTGRES_SCHEMA}
    open-in-view: false
  flyway:
    schemas: ${POSTGRES_SCHEMA}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  session:
    timeout: ${SESSION_TIMEOUT_SECONDS}
    redis:
      namespace: ${REDIS_NAMESPACE}

minio:
  endpoint: http://${MINIO_HOST}:${MINIO_PORT}
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket-name: ${MINIO_BUCKET_NAME}

logging:
  level:
    root: INFO

frontend:
  url: ${FRONTEND_URL}
