spring:
  config:
    import: optional:file:.env.dev[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      default_schema: ${POSTGRES_SCHEMA}
    open-in-view: false
  flyway:
    schemas: ${POSTGRES_SCHEMA}

server:
  servlet:
    session:
      timeout: 3600
      cookie:
        name: JSESSIONID
        http-only: true
        secure: false
  port: 8080

logging:
  level:
    root: info
