
# GET DIRECTORY INFO REQUESTS

### GET directory info, valid path to directory
GET localhost:8080/api/directory?path=test2/

### GET directory info, directory not created
GET localhost:8080/api/directory?path=test/

### GET directory info, valid path to file
GET localhost:8080/api/directory?path=test2/1.txt

### GET directory info, invalid path
GET localhost:8080/api/directory?path=test2//inner/

### GET directory info, empty path
GET localhost:8080/api/directory?path=

# CREATY EMPTY DIRECTORY REQUESTS

### POST (create) empty directory, valid path
POST localhost:8080/api/directory?path=test2/inner4/

### POST (create) empty directory, invalid path
POST localhost:8080/api/directory?path=test//inner/

### POST (create) empty directory, empty path
POST localhost:8080/api/directory?path=

### POST (create) empty directory, parent path not exists
POST localhost:8080/api/directory?path=test7/inner/inner2/

### POST (create) empty directory, directory already exists
POST localhost:8080/api/directory?path=test/